// Eventos: substitua imagem e alt neste arquivo quando novas fotografias oficiais estiverem disponíveis.
export const events = [
  {
    titulo: 'Bazar de artesanato',
    descricao: 'Venda beneficente de peças de artesanato, roupas e acessórios doados pela comunidade.',
    imagem: new URL('../img/eventos/evento_artesanato.webp', import.meta.url).href,
    width: 1200,
    height: 1600,
    alt: 'Voluntárias do GGCC em uma banca de artesanato ao ar livre',
    icone: 'sparkles',
    categoria: 'Evento beneficente',
  },
  {
    titulo: 'Jantar italiano',
    descricao: 'Tradicional jantar beneficente com pratos típicos para arrecadar recursos.',
    imagem: new URL('../img/eventos/evento_italiano.webp', import.meta.url).href,
    width: 720,
    height: 1280,
    alt: 'Salão decorado para o jantar italiano beneficente',
    icone: 'utensils',
    categoria: 'Gastronomia solidária',
  },
  {
    titulo: 'Leilão de gado',
    descricao: 'Evento anual integrado ao leilão da Paróquia, com animais doados pela comunidade.',
    imagem: '',
    width: null,
    height: null,
    alt: 'Fotografia do leilão de gado',
    icone: 'gavel',
    categoria: 'Arrecadação',
  },
  {
    titulo: 'Chá beneficente',
    descricao: 'Encontro que ocorre a realização do bingo com prêmio especial e alimentos preparados para a ocasião.',
    imagem: new URL('../img/eventos/evento_cha.webp', import.meta.url).href,
    width: 590,
    height: 443,
    alt: 'Salão preparado para o chá beneficente',
    icone: 'cup',
    categoria: 'Encontro beneficente',
    date: '2026-09-13',
    time: '14:00',
    utcOffset: '-03:00',
    albumId: 'cha-beneficente',
  },
  {
    titulo: 'Barraca do Pastel',
    descricao:
      'Ação beneficente promovida em diferentes períodos do ano, com venda de pastéis para arrecadar recursos para o grupo.',
    imagem: new URL('../img/eventos/evento_pastel.webp', import.meta.url).href,
    width: 1600,
    height: 1200,
    alt: 'Voluntárias trabalhando na Barraca do Pastel',
    icone: 'pastel',
    categoria: 'Gastronomia solidária',
  },
];
