// Galeria oficial: adicione, remova ou substitua fotografias somente neste arquivo.
// Use featured: true nas imagens que também devem aparecer na página inicial.
export const gallery = [
  {
    src: new URL('../img/galeria_1.webp', import.meta.url).href,
    width: 960,
    height: 686,
    alt: 'Voluntárias e voluntários reunidos em uma sala durante atividade do GGCC',
    featured: true,
  },
  {
    src: new URL('../img/galeria_2.webp', import.meta.url).href,
    width: 1448,
    height: 1086,
    alt: 'Grupo de voluntárias reunido atrás de uma mesa com alimentos preparados',
    featured: true,
  },
  {
    src: new URL('../img/galeria_3.webp', import.meta.url).href,
    width: 1600,
    height: 1200,
    alt: 'Voluntários ao lado de um veículo carregado com cestas e alimentos doados',
    featured: true,
  },
  {
    src: new URL('../img/galeria_4.webp', import.meta.url).href,
    width: 1600,
    height: 1200,
    alt: 'Voluntários reunidos ao redor de alimentos doados em uma área coberta',
    featured: true,
  },
  {
    src: new URL('../img/galeria_5.webp', import.meta.url).href,
    width: 1200,
    height: 1600,
    alt: 'Voluntários do GGCC atrás de uma mesa com produtos embalados para ação beneficente',
    featured: true,
  },
  {
    src: new URL('../img/galeria_6.webp', import.meta.url).href,
    width: 1600,
    height: 1200,
    alt: 'Equipe do GGCC reunida ao lado de uma caminhonete e de uma faixa do grupo',
    featured: true,
  },
  {
    src: new URL('../img/galeria_7.webp', import.meta.url).href,
    width: 1600,
    height: 768,
    alt: 'Salão com mesas ocupadas durante evento beneficente do GGCC',
  },
  {
    src: new URL('../img/galeria_8.webp', import.meta.url).href,
    width: 1280,
    height: 961,
    alt: 'Voluntárias exibindo produtos decorados e embalados para venda beneficente',
  },
  {
    src: new URL('../img/galeria_9.webp', import.meta.url).href,
    width: 1280,
    height: 960,
    alt: 'Grupo de mulheres reunido durante confraternização em um salão',
  },
  {
    src: new URL('../img/galeria_10.webp', import.meta.url).href,
    width: 1280,
    height: 960,
    alt: 'Voluntárias do GGCC com camisetas laranja reunidas para uma fotografia',
  },
  {
    src: new URL('../img/galeria_11.webp', import.meta.url).href,
    width: 1200,
    height: 1600,
    alt: 'Voluntárias trabalhando ao redor de uma mesa com alimentos em uma cozinha',
  },
  {
    src: new URL('../img/galeria_12.webp', import.meta.url).href,
    width: 1600,
    height: 1200,
    alt: 'Equipe da barraca do pastel reunida atrás da bancada de preparo',
  },
  {
    src: new URL('../img/galeria_13.webp', import.meta.url).href,
    width: 590,
    height: 443,
    alt: 'Voluntárias alinhadas em um palco durante cerimônia do GGCC',
  },
  {
    src: new URL('../img/galeria_14.webp', import.meta.url).href,
    width: 590,
    height: 443,
    alt: 'Voluntárias do GGCC reunidas em uma área arborizada durante atividade externa',
  },
  {
    src: new URL('../img/galeria_15.webp', import.meta.url).href,
    width: 590,
    height: 443,
    alt: 'Grupo de voluntárias posando atrás de uma mesa decorada em vermelho e branco',
  },
];
